const MODIFICATION_TYPES = {
    BUFF_FIXED: 'BUFF_FIXED',
    BUFF_PERCENTAGE: 'BUFF_PERCENTAGE',
    DEBUFF_FIXED: 'DEBUFF_FIXED',
    DEBUFF_PERCENTAGE: 'DEBUFF_PERCENTAGE',
} as const;

export {
    MODIFICATION_TYPES,
}