const DEFAULT_STATS = {
    attack: 0,
    defence: 0,
    isAlive: 1,
    hp: 1,
    totalHp: 1,
};

// "tipo de modificacion", NO "tipo modificado."
const MODIFICATION_TYPES = {
    BUFF_FIXED: 'BUFF_FIXED',
    BUFF_PERCENTAGE: 'BUFF_PERCENTAGE',
    DEBUFF_FIXED: 'DEBUFF_FIXED',
    DEBUFF_PERCENTAGE: 'DEBUFF_PERCENTAGE',
} as const;

const DEFAULT_STAT_MODIFIERS = {
    [MODIFICATION_TYPES.BUFF_FIXED]: 0,
    [MODIFICATION_TYPES.BUFF_PERCENTAGE]: 0,
    [MODIFICATION_TYPES.DEBUFF_FIXED]: 0,
    [MODIFICATION_TYPES.DEBUFF_PERCENTAGE]: 0,
};

export { DEFAULT_STATS, MODIFICATION_TYPES, DEFAULT_STAT_MODIFIERS };