import {IDuration, IStatusAppliedOnObject, ITimesUsed} from '../interfaces/Status.interface';

const STATUS_DURATIONS: {
    TEMPORAL: 'TEMPORAL',
    PERMANENT: 'PERMANENT'
} = {
  TEMPORAL: 'TEMPORAL',
  PERMANENT: 'PERMANENT',
};

const STATUS_SOURCE: {
    STATS: 'stats'
    ORIGIN_STATS: 'originalStats'
} = {
  STATS: 'stats',
  ORIGIN_STATS: 'originalStats',
};

const STATUS_WHEN_TO_APPLY: {
    ONCE: 'ONCE'
    PER_ACTION: 'PER_ACTION'
} = {
  ONCE: 'ONCE',
  PER_ACTION: 'PER_ACTION',
};

const STATUS_TYPE: {
    BUFF_FIXED: 'BUFF_FIXED'
    BUFF_PERCENTAGE: 'BUFF_PERCENTAGE'
    DEBUFF_FIXED: 'DEBUFF_FIXED'
    DEBUFF_PERCENTAGE: 'DEBUFF_PERCENTAGE'
} = {
  BUFF_FIXED: 'BUFF_FIXED',
  BUFF_PERCENTAGE: 'BUFF_PERCENTAGE',
  DEBUFF_FIXED: 'DEBUFF_FIXED',
  DEBUFF_PERCENTAGE: 'DEBUFF_PERCENTAGE',
};

const STATUS_APPLIED_ON: IStatusAppliedOnObject = {
  AFTER_ADD_STATUS: 'AFTER_ADD_STATUS',
  AFTER_ATTACK: 'AFTER_ATTACK',
  AFTER_DEFENCE: 'AFTER_DEFENCE',
  AFTER_DIE: 'AFTER_DIE',
  AFTER_REMOVE_STATUS: 'AFTER_REMOVE_STATUS',
  AFTER_TURN: 'AFTER_TURN',
  BEFORE_ADD_STATUS: 'BEFORE_ADD_STATUS',
  BEFORE_ATTACK: 'BEFORE_ATTACK',
  BEFORE_DEFENCE: 'BEFORE_DEFENCE',
  BEFORE_DIE: 'BEFORE_DIE',
  BEFORE_REMOVE_STATUS: 'BEFORE_REMOVE_STATUS',
  BEFORE_TURN: 'BEFORE_TURN',
};

const DEFAULT = {
  appliedOn: STATUS_APPLIED_ON.AFTER_TURN,
  durationType: STATUS_DURATIONS.PERMANENT,
  whenToApply: STATUS_WHEN_TO_APPLY.ONCE,
  name: 'default status',
  statsAffected: [],
  totalTimesApplied: 0,
  totalStatsChanged: {},
};

export {
  STATUS_APPLIED_ON,
  DEFAULT,
  STATUS_TYPE,
  STATUS_DURATIONS,
  STATUS_SOURCE,
  STATUS_WHEN_TO_APPLY,
};
